Algoritmo "Disney"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 7/20/2024
Var
// Seção de Declarações das variáveis 
   Dinheiro: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Quanto dinheiro voce tem?")
   Leia(Dinheiro)
   Se(dinheiro >= 1000) entao
      Escreval("Partiu Disney")
   Senao
      Escreval("Nao vai da nao")
   FimSe
Fimalgoritmo